[sobel]
threshold = 2.0
window_size_us = 350.0
filter_dead_pixels = true

[canny]
low_threshold = 0.5
high_threshold = 2.0
window_size_us = 350.0
filter_dead_pixels = true

[log]
threshold = 0.5
window_size_us = 350.0
filter_dead_pixels = true

[display]
show_ground_truth = true
metrics_update_hz = 10
